### ISSUE TITLE
Custom DocType - ignoring type generation

### ISSUE THREAD

**Issue by YacineGhoulam** [nikkothari22/frappe-types#17]
App Name: sante_direct
Doctype Name: --name of my custom doctype--
Do you want to generate types for child tables too? [y/N]: y
Do you want to generate types for custom fields too if exists? [y/N]: y

Generating types file for pharmacies in sante_direct
Custom DocType - ignoring type generation

**Comment by nikkothari22** [comment]
Hey @YacineGhoulam can you provide more details? What's the exact issue?

**Comment by YacineGhoulam** [comment]
Hi @nikkothari22 ,

I created some custom doctypes.

When I want to generate types for these doctypes it gives me an error: Custom DocType - ignoring type generation

It gives me this error with any doctype that I have created and has the "Custom" field checked (I cant uncheck it).

For context, I can generate types for doctypes that are predefined (like the User doctype)

**Comment by nikkothari22** [comment]
Yes, Frappe Types is a developer tool, so it's only meant for doctypes that are defined by developers in custom apps.

If you're developing a Frappe app, you should turn on developer mode on your local machine so that you can make doctypes that get added to your custom app.

**Comment by YacineGhoulam** [comment]
@nikkothari22  
I did activate developer mode. But as the error says, it refuses to generate types for custom doctypes.

**Comment by nikkothari22** [comment]
Yes that's by design. Custom doctypes are only created on production sites.

If you want to create a doctype for your app, it should not be of type "Custom" - hence developer mode needs to be enabled for you to be able to uncheck it.

**Comment by YacineGhoulam** [comment]
Ah Ok I understand Now Thank you!
